import passarinho from '../../../../public/audios/passarinho-que-gostava-de-cantar-lavinia.mp3';
import obra from '../../../assets/audios/exemplo-da-obra-rick-nascimento.mp3';

export const dataAccordionHinos = [
  {
    id: 1,
    titulo: 'Passarinho Que Gostava de Cantar',
    linkYoutube: 'https://www.youtube-nocookie.com/embed/WGSh3g5u0XA',
    audio: passarinho,
    hino: [
      'Existia um passarinho',
      'Que gostava de cantar',
      'Mas um dia apareceu um',
      'Homem muito, muito mal',
      'E prendeu o passarinho',
      'Que gostava de cantar',
      '',
      'Nunca mais cantou',
      'Nunca mais voou',
      'Passarinho na gaiola',
      'Triste ele ficou',
      '',
      'Mas um dia apareceu um',
      'Homem muito, muito bom',
      'E soltou o passarinho',
      'Que gostava de cantar',
      '',
      'Da gaiola saiu',
      'Da tristeza saiu',
      'Voa, voa, passarinho',
      'Que Deus te soltou',
      '',
      'Canta, passarinho',
      'Louva ao teu Senhor',
      'Canta e louva, passarinho',
      'Que Deus te soltou',
      '',
      'E agora o passarinho',
      'Está livre pra voar',
      'Não somente pra voar',
      'Mas também para cantar!',
      '',
      'Canta, passarinho',
      'Louva ao teu Senhor',
      'Canta e voa, passarinho',
      'Que Deus te soltou',
      '',
      'Canta, meus irmãos',
      'Louva ao teu Senhor',
      'Canta e louva, meus irmãos',
      'Que Deus nos soltou!',
      '',
      'Que Deus nos soltou',
      '',
      'Voa e canta, passarinho',
      'Na presença do Senhor',
      'Voa e canta, passarinho',
      'Que o Senhor já te soltou',
    ],
  },
  {
    id: 2,
    titulo: 'Exemplo de Obra',
    linkYoutube: 'https://www.youtube-nocookie.com/embed/qpMGp2CZ-yw',
    audio: obra,
    hino: [
      'Sempre orando e buscando nosso Deus',
      'Caminhando e vivendo pela fé',
      'Sabe que se para de buscar o nosso bom Deus',
      'Amanhã pode não estar em pé',
      'Um sorriso na face escondendo a alma',
      'Escondendo a tristeza mas Deus pede calma',
      '',
      'Oh! Conserva o 22 porque eu sou contigo',
      'Oh! Confia na palavra eu sou o teu amigo',
      '',
      'Dividir o que não tem com o teu irmão',
      'Mas Deus sabe que é de um sincero coração',
      'Não quer nem saber o que o vizinho diz',
      'Que ser crente nesta igreja não é ser feliz',
      '',
      'A ciência não resolve os seus problemas',
      'Por isso ele tem Deus e canta seus poemas',
      'O segredo do louvor',
      'Sua maior alegria é louvar ao senhor',
      'Louvai o senhor, louvai o senhor',
      'Louvai a Deus',
      'Toda honra, toda glória seja dada a Deus',
      '',
      'É homem fiel não desiste',
      'Gosta de levar alegria a quem tá triste',
      'O inimigo quer vê-lo de cabeça baixa',
      'Mas irmão não desanima e fica na batalha',
      'Ele sabe que tem Deus no coração',
      'E na hora da batalha Deus estende a mão',
      'Deus estende a mão',
      '',
      'Dá bom testemunho dentro da igreja',
      'E lá fora honra a Deus com toda a certeza',
      'Honra pai honra a mãe honra a sua esposa',
      'Na verdade é Deus puro que sai da sua boca',
      'Não reclama da prova que está passando',
      '',
      'Ora de madrugada pra sentir o anjo',
      'É humilde é sincero é trabalhador',
      'Vai no culto e prega a doutrina do senhor',
      'É passado para trás e ainda perdoa',
      'Ama as pessoas ruins, e também as boas',
      'E também as boas',
      '',
      'Pede força pra que possa suportar a tudo',
      'E ainda ora e diz que é servo inútil',
      'Que é servo inútil',
      'E você que entrou hoje nesta oração',
      'E serviu a Deus de um sincero coração',
      '',
      'Só Deus sabe a guerra e prova que está ai',
      'Só Deus sabe a tristeza pra chegar aqui',
      'Coisas belas, coisas novas que Deus vai plantar',
      'E na tua cidade Deus te exaltará',
      'Marche agora soldado contra o inimigo',
      'Eu te chamei nesta guerra porque tu é homem de Deus',
      'Homem de Deus, tu és homem de Deus',
      'Toda honra e toda glória seja dada a Deus',
      '',
      'E você que entrou hoje nesta oração',
      'E serviu a Deus de um sincero coração',
      'Só Deus sabe a guerra e prova que está ai',
      'Só Deus sabe a tristeza pra chegar aqui',
      '',
      'Coisas belas, coisas novas que Deus vai plantar',
      'E na tua cidade Deus te exaltará',
      'Marche agora soldado contra o inimigo',
      'Eu te chamei nesta guerra porque tu',
      '',
      'É homem de Deus',
      'Homem de Deus, tu és homem de Deus',
      'Louvai a Deus',
      'Toda honra e toda glória seja dada a Deus',
    ],
  },
  {
    id: 3,
    titulo: 'Na Face Um Sorriso',
    linkYoutube: 'https://www.youtube-nocookie.com/embed/Yk7425DkMtM',
    audio: '../../../../public/audios/na-face-um-sorriso-emaiara.mp3',
    hino: [
      'Na face um sorriso, tentando ocultar',
      'A angústia da alma, a vontade de chorar',
      'Mostrando alegria, ao invés da aflição',
      'Que está no profundo, do seu coração',
      'Não quer que ninguém, te veja pedir',
      'Não quer que ninguém, te veja implorar',
      'Não quer com ninguém, sua dor dividir',
      'Não quer que ninguém, te veja chorar',
      '',
      'Recebe em sua casa, seus caros irmãos',
      'E nem se percebe da tua aflição',
      'Se alegra no dom que Deus te emprestou',
      'Mas na tua tristeza, ninguém te ajudou',
      'Agora, ouça bem, Deus vai te falar',
      'Eu sou teu amigo, não vou te deixar',
      'Consolo tua alma, te dou minhas mãos',
      'Te faço mais crente, e te arranco do chão',
    ],
  },
  {
    id: 4,
    titulo: 'Ninguém É Mais Feliz Que Nós',
    linkYoutube: 'https://www.youtube-nocookie.com/embed/OA-Ak-E0Wp8',
    audio: '../../../../public/audios/ninguem-e-mais-feliz-que-nos-sirley-valdecir.mp3',
    hino: [
      'Mesmo que os anos passem, até mesmo',
      'A distância nos separe, ficarão dentro de mim',
      'Os momentos que, felizes, nós passamos',
      'Quantas lutas enfrentamos',
      'A inveja e o que levantou enfim',
      '',
      'Com o Mestre, aprendemos ser valentes',
      'Vindo a guerra, de repente, jamais vamos recuar',
      'Pois, cingiu-nos de uma força onipotente',
      'Este Deus onisciente',
      'Certamente nós iremos triunfar',
      '',
      'Posso dizer: Ninguém é mais feliz que nós',
      'Foi um prazer cantar ouvindo a sua voz',
      'Quem cantar como cantamos vai sentir o que sentimos',
      'E, por isso, estamos juntos mesmo estando em outro lugar',
      'Eu sei que a saudade um dia vai me visitar',
      'Ou se a ilusão do mundo vir pra derrubar',
      'Perseguido ou desprezado, lembrarei que ao seu lado',
      'Eu descobri um dom Divino, o ato de cantar',
      '',
      'Seja humilde, nunca troque esta riqueza',
      'Não se esqueça que a beleza verdadeira é a interior',
      'Muito embora muitos não te compreendam',
      'O que Deus plantou em nós',
      'O mundo não pode entender',
      'Mesmo estando em qualquer outra cidade',
      'Levaremos à irmandade o que Deus nos ensinou',
      'Aumentando essa corrente excelente',
      'Mostrando a felicidade',
      'De cantar pra quem ainda não cantou',
      '',
      'Posso dizer: Ninguém é mais feliz que nós',
      'Foi um prazer cantar ouvindo a sua voz',
      'Quem cantar como cantamos vai sentir o que sentimos',
      'E, por isso, estamos juntos mesmo estando em outro lugar',
      'Eu sei que a saudade um dia vai me visitar',
      'Ou se a ilusão do mundo vir pra derrubar',
      'Perseguido ou desprezado, lembrarei que ao seu lado',
      'Eu descobri um dom Divino, o ato de cantar',
    ],
  },
  {
    id: 5,
    titulo: 'Deus Olha Para Mim',
    linkYoutube: 'https://www.youtube-nocookie.com/embed/jT5GGGYM0JM',
    audio: '../../../../public/audios/Deus-olha-pra-mim-thayslaine.mp3',
    hino: [
      'Era madrugada Deus te viu orar',
      'Angustiado com vontade de chorar',
      'E orando tu pediu ao Criador',
      'Que de ti tiraste toda aquela dor',
      'Já são dias que eu não consigo dormir',
      'Pois a aflição tomou meu coração',
      'A esperança já não encontro em mim',
      'E por isto eu te peço',
      'Deus olha pra mim',
      '',
      'Deus não te deixou',
      'Não vai te deixar',
      'No mundo sozinho você não está',
      'A prova é um teste pra você enfrentar',
      'Mas não desanime',
      'Deus vai te ajudar',
      '',
      'Era madrugada Deus te viu chorar',
      'Sem ninguém para enxugar as suas lágrimas',
      'Teus amigos não podiam te ajudar',
      'Pois a prova era grande em sua vida',
      'Já são dias que eu não consigo dormir',
      'Pois a aflição tomou meu coração',
      'A esperança já não encontro em mim',
      'E por isso te peço',
      'Deus olha pra mim',
      '',
      'Deus não te deixou',
      'Não vai te deixar',
      'No mundo sozinho você não está',
      'A prova é um teste pra você enfrentar',
      'Mas não desanime',
      'Deus vai te ajudar',
      '',
      'Deus não te deixou',
      'Não vai te deixar',
      'No mundo sozinho você não está',
      'A prova é um teste pra você enfrentar',
      'Mas não desanime',
      'Deus vai te ajudar',
    ],
  },
  {
    id: 6,
    titulo: 'Você é Especial',
    linkYoutube: 'https://www.youtube-nocookie.com/embed/GUE9H1G6h6I',
    audio: '../../../../public/audios/voce-e-especial-luana-dias.mp3',
    hino: [
      'O que se perde pelo ar é folha e pó',
      'O que não serve pra usar, vagueia só',
      'E você não vive só',
      'Você é vaso de valor',
      '',
      'Quem já nasceu tem que entender que já venceu',
      'Teve o direito de crescer, aconteceu',
      'Isto eu já sei de cor',
      'Você é vaso de valor',
      '',
      'Você precisa acreditar',
      'Que quem é filho, é herdeiro',
      'E quem nasceu pra governar',
      'Deus usa até no cativeiro',
      'Esse tempo vai passar',
      'Não desista de orar',
      'Ele é fiel e verdadeiro',
      '',
      'E se você disser pra mim',
      'Que já foi vaso, está quebrado',
      'E por enquanto está assim',
      'Jogado aos cantos, encostado',
      'Eu prefiro insistir que o Oleiro está aqui',
      'Pra mudar o seu estado',
      '',
      'Você é especial',
      'Quem te deu a vida, destruiu a forma',
      'Não fez outro igual',
      'Você ainda não perdeu',
      'Você não é folha, você é alguém',
      'No coração de Deus',
      '',
      'Você precisa acreditar',
      'Que quem é filho, é herdeiro',
      'E quem nasceu pra governar',
      'Deus usa até no cativeiro',
      'Esse tempo vai passar',
      'Não desista de orar',
      'Ele é fiel e verdadeiro',
      '',
      'E se você disser pra mim',
      'Que já foi vaso, está quebrado',
      'E por enquanto está assim',
      'Jogado aos cantos, encostado',
      'Eu prefiro insistir que o Oleiro está aqui',
      'Pra mudar o seu estado',
      '',
      'Você é especial',
      'Quem te deu a vida, destruiu a forma',
      'Não fez outro igual',
      'Você ainda não perdeu',
      'Você não é folha, você é alguém',
      'No coração de Deus',
      '',
      'Você é especial',
      'Quem te deu a vida, destruiu a forma',
      'Não fez outro igual',
      'Você ainda não perdeu',
      'Você não é folha, você é alguém',
      'No coração de Deus',
      '',
      'No coração de Deus',
    ],
  },
  {
    id: 7,
    titulo: 'Cana trilhada',
    linkYoutube: 'https://www.youtube-nocookie.com/embed/BDyViQoGAgM',
    audio: '../../../../public/audios/cana-trilhada-janaina.mp3',
    hino: [
      'Há momentos tão difíceis',
      'Não consegue acreditar',
      'Parece que Deus não existe',
      'É tão difícil de suportar',
      'Nada ainda está perdido',
      'Deus testa nossa fé',
      'Ele prova para o inimigo',
      'O quanto ama você',
      '',
      'À espera de um milagre',
      'A fé é um dom de Deus',
      'Creia na palavra',
      'Que Deus prometeu',
      'Pois, a fé que você não perdeu',
      'Se ainda respira é porque não morreu',
      'Se ainda fumega',
      'É o porque não se apagou',
      'A cana trilhada',
      'Jamais se quebrou',
      'Ter fé ensina',
      'A ter confiança',
      'Enquanto houver vida',
      'Haverá esperança',
      '',
      'As tuas causas jamais serão difíceis',
      'Quantas obras Deus te fez',
      'Deus não conhece a palavra impossível',
      'Só conhece o fundamento da fé',
      'E nada ainda está perdido',
      'Deus testa nossa fé',
      'Ele prova para o inimigo',
      'O quanto ele ama você',
      '',
      'À espera de um milagre',
      'A fé é um dom de Deus',
      'Creia na palavra',
      'Que Deus prometeu',
      'Pois, a fé que você não perdeu',
      'Se ainda respira é porque não morreu',
      'Se ainda fumega',
      'É o porque não se apagou',
      'A cana trilhada',
      'Jamais se quebrou',
      'Ter fé ensina',
      'A ter confiança',
      'Enquanto houver vida',
      'Haverá esperança',
      '',
      'À espera de um milagre',
      'A fé é um dom de Deus',
      'Creia na palavra',
      'Que Deus prometeu',
      'Pois, a fé que você não perdeu',
      'Se ainda respira é porque não morreu',
      'Se ainda fumega',
      'É o porque não se apagou',
      'A cana trilhada',
      'Jamais se quebrou',
      'Ter fé ensina',
      'A ter confiança',
      'Enquanto houver vida',
      'Haverá esperança',
    ],
  },
];
